# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - arm_0_joint
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
  gripper_controller:
    type: FollowJointTrajectory
    joints:
      - gripper_1_joint
      - gripper_2_joint